### ISSUE TITLE
Elementus tomes give an absurd amount of mana, oversight? Elementus 1.2.1-20.1

### ISSUE THREAD

**Issue by Vipibolt** [Nokunami/Elementus#1]
Hello, making this issue report that the tomes of this mod for Iron's Spells compat give +10000% mana when equipped, giving comical amounts that just cannot be used up. This feels like it was an accident in programming.
Will this be fixed alongside your primary objective of Tetra compatibility?
![2024-08-10_07 23 38](https://github.com/user-attachments/assets/502908c0-4df0-41f9-a93a-1fd1d6346536)
![2024-08-10_07 23 49](https://github.com/user-attachments/assets/bf32749b-625b-4213-8aa6-98d4aa0da939)

**Comment by Nokunami** [comment]
this will be fixed in the next release.

**Comment by ghost** [comment]
im having this problem as well

**Comment by Nokunami** [comment]
Fixed in 1.3.0
