### ISSUE TITLE
Minor incompatibility with alex's caves

### ISSUE THREAD

**Issue by Altay5704** [Nokunami/Elementus#4]
When Elementus is installed, the galena gauntlet doesn't work, as in the right click functionality just doesn't seem to trigger.

**Comment by Altay5704** [comment]
I've noticed this bug with a few other mods, so it might be a problem on ACs end.

**Comment by Nokunami** [comment]
It's a tag issue, if an item listed in the tag isn't registered (eg. Mod not installed so the item doesn't exist) the tag will unload causing this issue.

**Comment by Nokunami** [comment]
@Altay5704 just released a new version, is the issue fixed on your end?

**Comment by Altay5704** [comment]
Yes, the galena gauntlet is working fine now. Thanks for the fix!
